### ISSUE TITLE
Braces Auto-Completion Issue. 

### ISSUE THREAD

**Issue by Kehza** [Shopify/theme-check-vscode#48] opened 2021-09-08 15:00 UTC
Steps to repeat: 

1. Enter `{{  }}`
2. Now put a dash after the set of braces `{{-  }}`
3. It autocomplets to `{{--}}  }}`

**Comment by lorand-horvath** [comment] 2022-02-03 06:08
I can confirm this issue. It's quite annoying.

**Comment by charlespwd** [comment] 2022-02-03 21:34
This thing is the bane of me. This seems like an upstream bug but I may be mistaken. Tried every combination under the sun for those VS Code extension language configuration settings:

```
  "brackets": [
    ["{{", "}}"],
    ["{%-", "-%}"],
    ["{%-", "%}"],
    ["{%", "-%}"],
    ["{%", "%}"],
  ],
  "autoClosingPairs": [
    { "open": "{%", "close": "%}" },
    { "open": "{{", "close": "}}" },
    { "open": "<", "close": ">" },
    { "open": "[", "close": "]" },
    { "open": "'", "close": "'", "notIn": ["string", "comment"] },
    { "open": "\"", "close": "\"", "notIn": ["string"] }
  ],
  "autoCloseBefore": ".,-=}])>'\"` \n\t",
```

And it's never _not_ annoying. Only thing that _seems_ like it's better is not closing the dash. Since you might actually want to only do it on one side and not the other. But you would never want to not close the `{%%}`

Would disabling the autoclosing of the dashes be more acceptable?

e.g. only autoclose `{%|%}` but not the dash?


https://user-images.githubusercontent.com/4990691/152432657-26833aa1-71b5-44db-bafd-20c26bfc5c74.mp4

**Comment by lorand-horvath** [comment] 2022-02-04 07:51
>Would disabling the autoclosing of the dashes be more acceptable?

>e.g. only autoclose {%|%} but not the dash?

@charlespwd  Yup, that's the compromise solution.

**Closed** 2022-02-04 16:03 UTC
